/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DyDown: typeof import('./../src/components/dy-down/dy-down.vue')['default']
    DyForm: typeof import('./../src/components/dy-form/dy-form.vue')['default']
    DyFrom: typeof import('./../src/components/dy-form/dy-from.vue')['default']
    DyUpload: typeof import('./../src/components/dy-upload/dy-upload.vue')['default']
    ReImageVerify: typeof import('./../src/components/ReImageVerify/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Types: typeof import('./../src/components/dy-form/types/types.ts')['default']
    UseImageVerify: typeof import('./../src/components/ReImageVerify/useImageVerify.ts')['default']
    Utils: typeof import('./../src/components/dy-form/utils.ts')['default']
  }
}
